<?php

define('SECRET_KEY', 'secretToken123');

define("BOOLEAN", '1');
define("INTEGER", '2');
define("STRING", '3');

define("REQUEST_METHOD_NOT_VALID", 100);
define("REQUEST_CONTENTTYPE_NOT_VALID", 101);
define("API_NAME_REQUIRED", 102);
define("API_PARAM_REQUIRED", 103);
define("ACCESS_TOKEN_ERRORS", 104);
define("AUTHORIZATION_HEADER_NOT_FOUND", 105);
define("INVALID_USER_PASS", 106);
define("USER_NOT_ACTIVE", 107);
define("VALIDATE_PARAM_REQUIRED", 108);
define("VALIDATE_PARAM_DATATYPE", 109);
define("JWT_PROCESSING_ERROR", 110);
define("SUCCESSFULL_RESPONSE", 200);
define("API_NO_EXISTS", 400);
?>